export const CONTROL_CONFIGS = {
    string: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องกรอกข้อมูลก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนช่องว่าง เช่น "กรอกชื่อ"' },
        { key: 'maxLength', label: 'Max Length', type: 'number', hint: 'จำกัดตัวอักษรสูงสุดที่พิมพ์ได้' },
        { key: 'rows', label: 'Rows', type: 'number', hint: 'จำนวนบรรทัด (>1 = textarea)' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
        { key: 'readOnly', label: 'Read Only', type: 'toggle', hint: 'อ่านได้อย่างเดียว' },
    ],
    number: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องกรอกข้อมูลก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนช่องว่าง' },
        { key: 'min', label: 'Min', type: 'number', hint: 'ค่าต่ำสุดที่อนุญาต' },
        { key: 'max', label: 'Max', type: 'number', hint: 'ค่าสูงสุดที่อนุญาต' },
        { key: 'step', label: 'Step', type: 'number', hint: 'กดปุ่ม +/- เพิ่ม-ลดครั้งละเท่าไหร่ เช่น 5' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
        { key: 'readOnly', label: 'Read Only', type: 'toggle', hint: 'อ่านได้อย่างเดียว' },
    ],
    password: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องกรอกข้อมูลก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนช่องว่าง' },
        { key: 'showStrength', label: 'Show Strength', type: 'toggle', hint: 'แสดงแถบวัดความแข็งแรงของรหัสผ่าน' },
        { key: 'minLength', label: 'Min Length', type: 'number', hint: 'จำนวนตัวอักษรขั้นต่ำ' },
    ],
    email: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องกรอกข้อมูลก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'เช่น "name@example.com"' },
    ],
    select: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกค่าก่อนส่งฟอร์ม' },
        { key: 'enum', label: 'Options', type: 'options', hint: 'ตัวเลือกในดรอปดาวน์' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนยังไม่เลือก' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
    ],
    dropdown: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกค่าก่อนส่งฟอร์ม' },
        { key: 'enum', label: 'Options', type: 'options', hint: 'ตัวเลือกในดรอปดาวน์' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนยังไม่เลือก เช่น "เลือกรายการ..."' },
        { key: 'searchable', label: 'ค้นหาได้', type: 'toggle', hint: 'เปิดให้พิมพ์ค้นหาตัวเลือกได้' },
        { key: 'clearable', label: 'ล้างค่าได้', type: 'toggle', hint: 'แสดงปุ่มล้างค่าที่เลือก' },
        { key: 'maxHeight', label: 'ความสูงสูงสุด', type: 'text', hint: 'เช่น "300px"' },
    ],
    boolean: [
        { key: 'value', label: 'Default', type: 'toggle', hint: 'ค่าเริ่มต้น checked หรือไม่' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
    ],
    toggle: [
        { key: 'value', label: 'Default', type: 'toggle', hint: 'ค่าเริ่มต้น เปิด/ปิด' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
    ],
    date: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกวันที่ก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'เช่น "วว/ดด/ปปปป"' },
        { key: 'min', label: 'Min Date', type: 'text', hint: 'วันที่ต่ำสุด เช่น "2024-01-01"' },
        { key: 'max', label: 'Max Date', type: 'text', hint: 'วันที่สูงสุด เช่น "2026-12-31"' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
        { key: 'readOnly', label: 'Read Only', type: 'toggle', hint: 'อ่านได้อย่างเดียว' },
    ],
    datepicker: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกวันที่ก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'เช่น "เลือกวันที่"' },
        { key: 'minDate', label: 'Min Date', type: 'text', hint: 'วันที่ต่ำสุด เช่น "2024-01-01"' },
        { key: 'maxDate', label: 'Max Date', type: 'text', hint: 'วันที่สูงสุด เช่น "2026-12-31"' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
    ],
    slider: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลื่อนค่าก่อนส่งฟอร์ม' },
        { key: 'min', label: 'Min', type: 'number', hint: 'ค่าต่ำสุดของแถบเลื่อน' },
        { key: 'max', label: 'Max', type: 'number', hint: 'ค่าสูงสุดของแถบเลื่อน' },
        { key: 'step', label: 'Step', type: 'number', hint: 'เลื่อนครั้งละเท่าไหร่ เช่น 10' },
        { key: 'value', label: 'Default', type: 'number', hint: 'ค่าเริ่มต้นของแถบเลื่อน' },
        { key: 'unit', label: 'Unit', type: 'text', hint: 'หน่วย เช่น "%" หรือ "km"' },
        { key: 'showValue', label: 'แสดงค่า', type: 'toggle', hint: 'แสดงตัวเลขค่าปัจจุบัน' },
        { key: 'showTicks', label: 'แสดงขีด', type: 'toggle', hint: 'แสดงขีดบนแถบเลื่อน' },
        { key: 'showLabel', label: 'แสดง Label', type: 'toggle', hint: 'แสดง label min/max' },
        { key: 'size', label: 'ขนาด', type: 'text', hint: 'small, medium, large' },
        { key: 'color', label: 'สี', type: 'text', hint: 'สีแถบ เช่น "#3b82f6"' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
    ],
    rating: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องให้คะแนนก่อนส่งฟอร์ม' },
        { key: 'maxStars', label: 'Max Stars', type: 'number', hint: 'จำนวนดาวสูงสุด (default: 5)' },
        { key: 'value', label: 'Default', type: 'number', hint: 'จำนวนดาวเริ่มต้น' },
        { key: 'allowHalf', label: 'ครึ่งดาว', type: 'toggle', hint: 'อนุญาตให้เลือกครึ่งดาว (0.5)' },
        { key: 'showLabel', label: 'แสดงค่า', type: 'toggle', hint: 'แสดงตัวเลขคะแนน เช่น 3.5/5' },
        { key: 'color', label: 'สี', type: 'text', hint: 'สีดาว เช่น "#ffc107", "#ef4444"' },
        { key: 'size', label: 'ขนาด', type: 'text', hint: 'small, medium, large' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้แก้ไข' },
        { key: 'readOnly', label: 'Read Only', type: 'toggle', hint: 'อ่านได้อย่างเดียว' },
    ],
    fileupload: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องอัปโหลดไฟล์ก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนยังไม่เลือกไฟล์' },
        { key: 'maxFileSize', label: 'ขนาดไฟล์สูงสุด (bytes)', type: 'number', hint: 'เช่น 52428800 = 50MB' },
        { key: 'allowedTypes', label: 'ประเภทไฟล์', type: 'text', hint: 'เช่น "image/jpeg,image/png,application/pdf"' },
        { key: 'buttonLabel', label: 'ข้อความปุ่ม', type: 'text', hint: 'เช่น "Choose Files to Upload"' },
    ],
    searchbox: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกค่าก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'เช่น "ค้นหาและเลือก..."' },
        { key: 'multiple', label: 'Multiple', type: 'toggle', hint: 'เลือกได้หลายค่า' },
        { key: 'allowCreate', label: 'Allow Create', type: 'toggle', hint: 'อนุญาตให้สร้างค่าใหม่ที่ไม่มีในรายการ' },
    ],
    multipleupload: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องอัปโหลดไฟล์ก่อนส่งฟอร์ม' },
        { key: 'placeholder', label: 'Placeholder', type: 'text', hint: 'ข้อความแสดงตอนยังไม่เลือกไฟล์' },
        { key: 'allowedTypes', label: 'ประเภทไฟล์', type: 'text', hint: 'เช่น "image/jpeg,image/png"' },
        { key: 'maxFileSize', label: 'ขนาดไฟล์สูงสุด (bytes)', type: 'number', hint: 'เช่น 10485760 = 10MB' },
    ],
    label: [
        { key: 'value', label: 'Text', type: 'text', hint: 'ข้อความที่แสดง (ถ้าไม่ผูก databind)' },
        { key: 'bold', label: 'ตัวหนา', type: 'toggle', hint: 'แสดงข้อความตัวหนา' },
        { key: 'italic', label: 'ตัวเอียง', type: 'toggle', hint: 'แสดงข้อความตัวเอียง' },
        { key: 'fontSize', label: 'ขนาดตัวอักษร', type: 'text', hint: 'เช่น "18px", "1.5em"' },
        { key: 'multiline', label: 'หลายบรรทัด', type: 'toggle', hint: 'อนุญาตข้อความหลายบรรทัด' },
    ],
    link: [
        { key: 'value', label: 'Text', type: 'text', hint: 'ข้อความลิงก์ที่แสดง' },
        { key: 'href', label: 'URL', type: 'text', hint: 'URL ปลายทาง เช่น "https://..."' },
        { key: 'target', label: 'Target', type: 'text', hint: '"_blank" เปิดแท็บใหม่, "_self" เปิดแท็บเดิม' },
        { key: 'icon', label: 'Icon', type: 'text', hint: 'ไอคอนประกอบ เช่น "🔗"' },
        { key: 'iconPosition', label: 'Icon Position', type: 'text', hint: '"left" หรือ "right"' },
        { key: 'underline', label: 'ขีดเส้นใต้', type: 'toggle', hint: 'แสดงเส้นใต้ลิงก์' },
        { key: 'buttonStyle', label: 'สไตล์ปุ่ม', type: 'toggle', hint: 'แสดงเป็นปุ่มแทนลิงก์' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้คลิก' },
    ],
    image: [
        { key: 'value', label: 'Image URL', type: 'text', hint: 'URL ของรูปภาพ' },
        { key: 'width', label: 'Width', type: 'text', hint: 'ความกว้าง เช่น "200px"' },
        { key: 'height', label: 'Height', type: 'text', hint: 'ความสูง เช่น "120px"' },
        { key: 'borderRadius', label: 'Border Radius', type: 'text', hint: 'มุมโค้ง เช่น "50%" = วงกลม' },
        { key: 'objectFit', label: 'Object Fit', type: 'text', hint: 'วิธีแสดงรูป: cover, contain, fill' },
        { key: 'shadow', label: 'Shadow', type: 'toggle', hint: 'แสดงเงาใต้รูป' },
        { key: 'alt', label: 'Alt Text', type: 'text', hint: 'ข้อความอธิบายรูป (accessibility)' },
        { key: 'lazy', label: 'Lazy Load', type: 'toggle', hint: 'โหลดรูปเมื่อเลื่อนมาถึง' },
        { key: 'enlargeable', label: 'ขยายได้', type: 'toggle', hint: 'คลิกแล้วขยายรูปเต็มจอ' },
        { key: 'grayscale', label: 'Grayscale', type: 'toggle', hint: 'แสดงรูปขาวดำ' },
        { key: 'fallback', label: 'Fallback URL', type: 'text', hint: 'URL รูปสำรองถ้าโหลดไม่ได้' },
    ],
    badge: [
        { key: 'value', label: 'Text', type: 'text', hint: 'ข้อความใน badge' },
        { key: 'backgroundColor', label: 'สีพื้นหลัง', type: 'text', hint: 'เช่น "#3b82f6", "#ef4444"' },
        { key: 'color', label: 'สีตัวอักษร', type: 'text', hint: 'เช่น "#ffffff"' },
    ],
    icon: [
        { key: 'value', label: 'Icon', type: 'text', hint: 'emoji หรือ icon เช่น "⭐"' },
        { key: 'fontSize', label: 'ขนาด', type: 'text', hint: 'เช่น "24px", "2em"' },
        { key: 'color', label: 'สี', type: 'text', hint: 'เช่น "#3b82f6"' },
        { key: 'size', label: 'Size Preset', type: 'text', hint: 'small, medium, large' },
    ],
    progress: [
        { key: 'value', label: 'Value (%)', type: 'number', hint: 'เปอร์เซ็นต์ 0-100' },
        { key: 'showValue', label: 'Show Value', type: 'toggle', hint: 'แสดงตัวเลข % บนแถบ' },
        { key: 'color', label: 'Color', type: 'text', hint: 'สีแถบ เช่น "#3b82f6"' },
    ],
    qrcode: [
        { key: 'value', label: 'QR Data', type: 'text', hint: 'ข้อมูลที่เข้ารหัส เช่น URL' },
        { key: 'width', label: 'Width', type: 'number', hint: 'ความกว้าง (px)' },
        { key: 'height', label: 'Height', type: 'number', hint: 'ความสูง (px)' },
        { key: 'errorCorrectionLevel', label: 'Error Correction', type: 'text', hint: 'L, M, Q, H (สูงสุด = ทนต่อความเสียหาย)' },
        { key: 'margin', label: 'Margin', type: 'number', hint: 'ขอบรอบ QR (modules)' },
        { key: 'color', label: 'Color', type: 'text', hint: 'สี QR เช่น "#000000"' },
    ],
    pagebreak: [],
    calendar: [],
    calendargrid: [
        { key: 'editable', label: 'แก้ไขได้', type: 'toggle', hint: 'อนุญาตให้เพิ่ม/แก้ไขข้อมูลในปฏิทิน' },
    ],
    button: [
        { key: 'value', label: 'Button Text', type: 'text', hint: 'ข้อความบนปุ่ม' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้คลิก' },
    ],
    buttongroup: [
        { key: 'required', label: 'จำเป็น', type: 'toggle', hint: 'ต้องเลือกค่าก่อนส่งฟอร์ม' },
        { key: 'enum', label: 'Buttons', type: 'options', hint: 'รายการปุ่ม' },
        { key: 'orientation', label: 'Orientation', type: 'text', hint: '"horizontal" หรือ "vertical"' },
        { key: 'multiple', label: 'เลือกหลายค่า', type: 'toggle', hint: 'อนุญาตให้กดเลือกหลายปุ่มพร้อมกัน' },
        { key: 'disabled', label: 'Disabled', type: 'toggle', hint: 'ปิดไม่ให้คลิก' },
    ],
    pagination: [
        { key: 'total', label: 'Total Pages', type: 'number', hint: 'จำนวนหน้าทั้งหมด' },
        { key: 'maxButtons', label: 'Max Buttons', type: 'number', hint: 'จำนวนปุ่มหน้าที่แสดง' },
        { key: 'showPageInfo', label: 'แสดงข้อมูลหน้า', type: 'toggle', hint: 'แสดง "หน้า x จาก y"' },
        { key: 'showItemInfo', label: 'แสดงข้อมูลรายการ', type: 'toggle', hint: 'แสดง "แสดง 1-10 จาก 100"' },
    ],
    accordion: [],
    tabs:     [],
    card:     [],
    tree:     [],
    menu:     [],
    grid:     [],
    table:    [],
    form:     [],
    crud:     [],
    alertmodal: [
        { key: 'title', label: 'Title', type: 'text', hint: 'หัวข้อ alert' },
        { key: 'message', label: 'Message', type: 'text', hint: 'ข้อความใน alert' },
    ],
    confirmmodal: [
        { key: 'title', label: 'Title', type: 'text', hint: 'หัวข้อ confirm' },
        { key: 'message', label: 'Message', type: 'text', hint: 'ข้อความใน confirm' },
    ],
    modal: [
        { key: 'value', label: 'Button Text', type: 'text', hint: 'ข้อความปุ่มเปิด modal' },
    ],
    chart: [
        { key: 'chartType', label: 'Chart Type', type: 'text', hint: 'ประเภทกราฟ: bar, line, pie, doughnut, radar, area' },
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'xAxisKey', label: 'X Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน X' },
        { key: 'yAxisKey', label: 'Y Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน Y' },
        { key: 'nameKey', label: 'Name Key', type: 'text', hint: 'key สำหรับ label ของข้อมูล' },
        { key: 'dataKey', label: 'Data Key', type: 'text', hint: 'key สำหรับค่าข้อมูล' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
        { key: 'showGrid', label: 'Show Grid', type: 'toggle', hint: 'แสดงเส้น Grid' },
    ],
    chartsbar: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'xAxisKey', label: 'X Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน X' },
        { key: 'yAxisKey', label: 'Y Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน Y' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
        { key: 'showGrid', label: 'Show Grid', type: 'toggle', hint: 'แสดงเส้น Grid' },
    ],
    chartsline: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'xAxisKey', label: 'X Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน X' },
        { key: 'yAxisKey', label: 'Y Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน Y' },
        { key: 'curved', label: 'Curved', type: 'toggle', hint: 'เส้นโค้ง' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
        { key: 'showGrid', label: 'Show Grid', type: 'toggle', hint: 'แสดงเส้น Grid' },
    ],
    chartspie: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'nameKey', label: 'Name Key', type: 'text', hint: 'key สำหรับ label' },
        { key: 'dataKey', label: 'Data Key', type: 'text', hint: 'key สำหรับค่า' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
    ],
    chartsdoughnut: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'nameKey', label: 'Name Key', type: 'text', hint: 'key สำหรับ label' },
        { key: 'dataKey', label: 'Data Key', type: 'text', hint: 'key สำหรับค่า' },
        { key: 'innerRadius', label: 'Inner Radius (%)', type: 'number', hint: 'รัศมีวงใน เช่น 60' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
    ],
    chartsradar: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
    ],
    chartsarea: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'xAxisKey', label: 'X Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน X' },
        { key: 'yAxisKey', label: 'Y Axis Key', type: 'text', hint: 'ชื่อ field สำหรับแกน Y' },
        { key: 'fillOpacity', label: 'Fill Opacity', type: 'number', hint: 'ความโปร่งใส 0-1 เช่น 0.3' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
        { key: 'showGrid', label: 'Show Grid', type: 'toggle', hint: 'แสดงเส้น Grid' },
    ],
    chartsbubble: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
    ],
    chartsmixed: [
        { key: 'title', label: 'Title', type: 'text', hint: 'ชื่อกราฟ' },
        { key: 'showLegend', label: 'Show Legend', type: 'toggle', hint: 'แสดง Legend' },
        { key: 'showGrid', label: 'Show Grid', type: 'toggle', hint: 'แสดงเส้น Grid' },
    ],
};
