export const DEFAULT_LABELS = {
    addButton: 'เพิ่มข้อมูล',
    editButton: 'แก้ไข',
    deleteButton: 'ลบ',
    bulkDeleteButton: 'ลบที่เลือก',
    searchPlaceholder: 'ค้นหา...',
    modalAddTitle: 'เพิ่มข้อมูลใหม่',
    modalEditTitle: 'แก้ไขข้อมูล',
    saveButton: 'บันทึก',
    cancelButton: 'ยกเลิก',
    confirmDeleteTitle: 'ยืนยันการลบ',
    confirmDeleteMessage: 'คุณต้องการลบข้อมูลนี้หรือไม่?',
    confirmBulkDeleteMessage: 'คุณต้องการลบข้อมูลที่เลือกหรือไม่?',
    emptyMessage: 'ไม่มีข้อมูล',
    actionsHeader: '',
    selectedCount: 'รายการที่เลือก',
    selectAllHeader: '',
    bulkEditButton: 'เลือกรายการ',
    bulkEditCancelButton: 'ยกเลิกเลือก',
};
